# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         mytop
version:      1.9.1
version_from: mytop
installdirs:  site
requires:
    DBD::mysql:                    1
    DBI:                           1.13
    Term::ReadKey:                 2.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
